### PR TITLE
core: fix segfaults when the HOME environment variable is not set

### LINKED ISSUE #1148: picom --invert-color-include fails when the HOME env is unset
when i run picom in an environment where HOME is unset
then this does not work = the colors of chromium are not inverted

```
picom --invert-color-include 'class_g="Chromium-browser"'
```

fixed by setting HOME to an empty tempdir

picom version 10.2

<details>
<summary>
test-picom.py
</summary>

im calling picom from python, so this looks like

```py
#!/usr/bin/env python3

# required packages: tigervnc picom chromium

import os
import subprocess
import tempfile
import time

vnc_display = ":2"

args = [
    "Xvnc",
    # dont require a password
    "-SecurityTypes", "none",
    "-geometry", "1024x768", # default: 1024x768
    "-depth", "16", # default: 24
    "-FrameRate", "10", # maximum frame rate. default: 60
    "-localhost", # accept connections only from localhost
    vnc_display,
]
proc_xvnc = subprocess.Popen(
    args,
)
time.sleep(1)

args = ["vncviewer", vnc_display]
proc_vncviewer = subprocess.Popen(
    args,
)
time.sleep(1)

# minimal env: only PATH is set
custom_env = {
    "PATH": os.environ["PATH"],
    "DISPLAY": vnc_display,
    # setting HOME is required to fix "picom --invert-color-include"
    #"HOME": tempfile.mkdtemp(suffix="-temp_home"),
}

args = [
    "picom",

    # invert colors of chromium window
    "--invert-color-include", 'class_g="Chromium-browser"',

    # invert colors of all windows, also "save file" dialogs
    #"--invert-color-include", 'name ~= "."',

    # dont invert colors for the "feh" image viewer
    #"--invert-color-include", 'class_g != "feh"',

    # fix "picom --invert-color-include" with unset HOME
    "--config", "/dev/null",
]
proc_picom = subprocess.Popen(
    args,
    env=custom_env,
)
time.sleep(1)

args = ["chromium"]
proc_chromium = subprocess.Popen(
    args,
    env=custom_env,
)
time.sleep(5)

proc_vncviewer.kill()
proc_chromium.kill()
proc_picom.kill()
proc_xvnc.kill()
```

</details>

### PR DESCRIPTION
**Pull request by absolutelynothelix**
fixes #1148.

### CODE REVIEW

File: src/config.c [hunk 1]
```diff
@@ -596,23 +596,25 @@ char *locate_auxiliary_file(const char *scope, const char *path, const char *inc
 	// Fall back to searching in user config directory
 	scoped_charp picom_scope = mstrjoin("/picom/", scope);
 	scoped_charp config_home = (char *)xdg_config_home();
-	char *ret = locate_auxiliary_file_at(config_home, picom_scope, path);
-	if (ret) {
-		return ret;
+	if (config_home && strlen(config_home)) {
```
Comment (yshui) [inline src/config.c]: do we need to check strlen?

Comment (absolutelynothelix) [reply src/config.c]: hm, it seems that the `xdg_config_home` function can't return an empty string. let's get rid of this check then.

**Review by yshui — APPROVED** [review]
lgtm
