### PR TITLE
backend: fix resize factor calculation

### LINKED ISSUE #1088: Visual artifacts when using blur and urxvt terminal
### Platform

Debian 12, amd64
### GPU, drivers, and screen setup

single monitor, Ryzen 5 3400G with integrated gpu, variable refresh rate, 144hz
`glxinfo -B `output:
```name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.6, DRM 3.49, 6.1.0-9-amd64) (0x15d8)
    Version: 22.3.6
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1284 MB, largest block: 1284 MB
    VBO free aux. memory - total: 2859 MB, largest block: 2859 MB
    Texture free memory - total: 1284 MB, largest block: 1284 MB
    Texture free aux. memory - total: 2859 MB, largest block: 2859 MB
    Renderbuffer free memory - total: 1284 MB, largest block: 1284 MB
    Renderbuffer free aux. memory - total: 2859 MB, largest block: 2859 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 5120 MB
    Currently available dedicated video memory: 1284 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.6, DRM 3.49, 6.1.0-9-amd64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### Environment
AwesomeWM

### picom version

vgit-4e6dd
<details>
<summary>Diagnostics</summary>
**Version:** vgit-4e6dd

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/samsepi0l/.config/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.6, DRM 3.49, 6.1.0-9-amd64)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: radeonsi
 * GL: AMD
* GL renderer: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.6, DRM 3.49, 6.1.0-9-amd64)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
# ░█▀█░▀█▀░█▀▀░█▀█░█▄█░░░░█▀▀░█▀█░█▀█░█▀▀
# ░█▀▀░░█░░█░░░█░█░█░█░░░░█░░░█░█░█░█░█▀▀
# ░▀░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░░▀▀▀░▀▀▀░▀░▀░▀░░
#
#  X compositor configuration

# ░█▀▀░█░█░█▀█░█▀▄░█▀█░█░█
# ░▀▀█░█▀█░█▀█░█░█░█░█░█▄█
# ░▀▀▀░▀░▀░▀░▀░▀▀░░▀▀▀░▀░▀

shadow = false;
shadow-radius = 0;
shadow-opacity = 0;
shadow-offset-x = 0;
shadow-offset-y = 0;

 shadow-red = 0
 shadow-green = 0
 shadow-blue = 0
#shadow-color = "#000000";

shadow-exclude = [
#	"name = 'Notification'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"class_g = 'slop'",
#	"class_g = 'Firefox' && argb",
#	"class_g = 'Rofi'",
	"_GTK_FRAME_EXTENTS@:c",
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# ░█▀▀░█▀█░█▀▄░▀█▀░█▀█░█▀▀
# ░█▀▀░█▀█░█░█░░█░░█░█░█░█
# ░▀░░░▀░▀░▀▀░░▀▀▀░▀░▀░▀▀▀

fading = false;
fade-in-step = 0.;
fade-out-step = 0;
fade-delta = 0;

fade-exclude = [];

no-fading-openclose = false;
no-fading-destroyed-argb = true;

# ░█▀█░█▀█░█▀█░█▀▀░▀█▀░▀█▀░█░█
# ░█░█░█▀▀░█▀█░█░░░░█░░░█░░░█░
# ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░░▀░░░▀░

inactive-opacity = 0.6;
frame-opacity = 1;
inactive-opacity-override = false;
active-opacity = 1.0;
inactive-dim = 0.0;

focus-exclude = [
	"class_g ?= 'mpv'"
];

# inactive-dim-fixed = 1.0;

#opacity-rule = [ 
#	"70:class_g = 'URxvt'",
#	"80:class_g = 'UXTerm'",
#	"80:class_g = 'XTerm'"
#]

# ░█▀▄░█░░░█░█░█▀▄░█▀▄░▀█▀░█▀█░█▀▀
# ░█▀▄░█░░░█░█░█▀▄░█▀▄░░█░░█░█░█░█
# ░▀▀░░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀

blur: {
	method = "dual_kawase";
    strength = 9.0;
	deviation = 1.0;
	kernel = "11x11gaussian";
}

blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;
# blur-kern = "3x3box";

# blur-background-exclude = [
# 	"class_g = 'slop'",
# 	"class_g = 'argb'",
# 	"name = 'rofi - Global Search'",
# 	"_GTK_FRAME_EXTENTS@:c"
# ];

# ░█▀▀░█▀▀░█▀█░█▀▀░█▀▄░█▀█░█░░░░░█▀▀░█▀▀░▀█▀░▀█▀░▀█▀░█▀█░█▀▀░█▀▀
# ░█░█░█▀▀░█░█░█▀▀░█▀▄░█▀█░█░░░░░▀▀█░█▀▀░░█░░░█░░░█░░█░█░█░█░▀▀█
# ░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░░░▀▀▀░▀▀▀░░▀░░░▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀

daemon = false;
backend = "glx";
vsync = false;
dbus = false;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = false;
detect-client-opacity = true;
#refresh-rate = 144;
# use-ewmh-active-win = true;
# unredir-if-possible = false;
# unredir-if-possible-delay = 0;

unredir-if-possible-exclude = [];

detect-transient = true;
detect-client-leader = true;
resize-damage = 1;

invert-color-include = [];

glx-no-stencil = true;
# glx-no-rebind-pixmap = false;
use-damage = true;
# xrender-sync-fence = true;

# glx-fshader-win = "";
# force-win-blend = false;

# no-ewmh-fullscreen = false;
# max-brightness = 1.0;

transparent-clipping = false;

log-level = "warn";
log-file = "/home/samsepi0l/.cache/picom-log.log";
show-all-xerrors = true;
# write-pid-path = '/path/to/your/mom';

wintypes: {
	tooltip = { fade = false; shadow = false; focus = false; };
	normal = { shadow = false; };
	dock = { shadow = false; };
	dnd = { shadow = false; };
	popup_menu = { shadow = false; focus = false; opacity = 1; };
	dropdown_menu = { shadow = false; focus = false; };
	above = { shadow = false; };
	splash = { shadow = false; };
	utility = { focus = false; shadow = false; blur-background = false; };
	notification = { shadow = false; };
	desktop = { shadow = false; blur-background = false; };
	menu = { focus = false; };
	dialog = { shadow = false; };
};

```
</details>

### Steps of reproduction

1. Enable blur (dual_kawase in my case)
2. Enable 32 bit depth and make the background transparent in urxvt
3. Launch urxvt without any other window open
### Expected behavior
smooth blur on urxvt, with a single window open
this does not happen with kitty terminal or st
### Current Behavior
{This only happens with urxvt when it's the only program open on a screen, even bringing another urxvt window fixes it} blur divided into blocky lines, blurs the text on the terminal itself looks especially bad when selecting something (I'm doing that in the screenshot)
alt text

### OpenGL trace

[picom.txt](https://github.com/yshui/picom/files/11919433/picom.txt)

### Other details

https://github.com/yshui/picom/assets/131687037/16a56cc1-2c1e-4516-9c7f-33625b3fd433

### PR DESCRIPTION
**Pull request by absolutelynothelix**
the corresponding regions need to be resized once for each window in the stack above the damaged window including the damaged window itself. we were off by one.

fixes #1088

### CODE REVIEW

**Comment by yshui** [comment]
hmm, shouldn't this be `t->stacking_rank + 1`?

File: src/backend/backend.c [hunk 1]
```diff
@@ -153,7 +153,7 @@ void paint_all_new(session_t *ps, struct managed_win *t) {
 		//
 		// TODO(yshui): maybe we don't need to resize reg_damage, only reg_paint?
 		int resize_factor = 1;
-		if (t) {
+		if (t && t->stacking_rank > 1) {
 			resize_factor = t->stacking_rank;
```
Comment (yshui) [inline src/backend/backend.c]: hmm, maybe this should be `t->stacking_rank + 1`?

Comment (absolutelynothelix) [reply src/backend/backend.c]: if you mean `resize_factor = t->stacking_rank + 1` then i think that's too pessimistic and we're already pessimistic according to the comment above.

Comment (yshui) [reply src/backend/backend.c]: it's not pessimistic, it is _correct_. the region needs to be extend once for each window below in the stack (including the window itself). we were off-by-one.

Comment (absolutelynothelix) [reply src/backend/backend.c]: makes sense.

**Comment by yshui** [comment]
thanks. i'll make a note that we need to look at damage resizing again in the future. the region that needs to be repaint for blur is different for each level in the stack, but right now we are using the same one for all windows.
